# Generated by Django 3.1.7 on 2021-03-12 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pytanie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tekst_pytania', models.CharField(max_length=300)),
                ('data_publikacji', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Wybor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tekst_odpowiedzi', models.CharField(max_length=300)),
                ('glosy', models.IntegerField(default=0)),
                ('pytanie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ankieta.pytanie')),
            ],
        ),
    ]
