# Generated by Django 3.1.7 on 2021-07-06 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glowna', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
