# Generated by Django 3.1.7 on 2021-09-13 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('glowna', '0002_delete_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kawy_tab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodzaj', models.CharField(max_length=100, verbose_name='full name')),
                ('ilosc', models.IntegerField(max_length=100, verbose_name='full name')),
                ('cena', models.IntegerField(max_length=100, verbose_name='full name')),
            ],
        ),
    ]
