# Generated by Django 3.1.7 on 2021-09-13 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glowna', '0003_kawy_tab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kawy_tab',
            name='cena',
            field=models.IntegerField(verbose_name='full name'),
        ),
        migrations.AlterField(
            model_name='kawy_tab',
            name='ilosc',
            field=models.IntegerField(verbose_name='full name'),
        ),
    ]
