# Generated by Django 3.1.7 on 2021-09-13 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glowna', '0004_auto_20210913_1137'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Kawy_tab',
        ),
    ]
